### ISSUE TITLE
压缩机吞沙粒

### ISSUE THREAD

**Issue by dandanlong123** [LordIdra/CompressedMachines#1]
Error Generated: 2021-07-03-20-42

Java Environment:
  Operating System: Linux
  Java Version: 16.0.1

Server Software: Yatopia
  Build: git-Yatopia-ver/1.16.5-115 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun v1.1.9_货运极致优化
  Caused by: CompressedMachines v1.0.0

Installed Addons (59)
  + EcoPower DEV - 1 (git 53445ee5)
  + SimpleUtils DEV - 3 (git ee043364)
  + CompressedMachines 1.0.0
  + ExtraGear DEV - 12 (git 4570ea2c)
  + ClayTech violet-1.2.24
  + SFCalc UNOFFICIAL
  + EMC2 UNOFFICIAL
  + SlimeChem MODIFIED
  + NewBegginings 1.0.0
  + BloodAlchemy ALPHA - CH
  + SlimefunWarfare UNOFFICIAL
  + ExoticGarden DEV - 75 (git 6c3e5412)
  + Endrex 1.1.0
  + Liquid DEV - 10 (git 2277a85b)
  + SoulJars UNOFFICIAL
  + SlimyRepair 1.0.0
  + ExtraTools 1.2
  + HALsAddon 12
  + SlimefunOreChunks UNOFFICIAL
  + SlimeVoid 1.0
  + EnderPanda 1.0
  + PrivateStorage UNOFFICIAL
  + DankTech 1.2.6.1
  + SlimefunItemExpansion 1.0.2
  + SimpleStorage MODIFIED
  + SlimefunAddon 1.0.0
  + BetterFarming 1
  + Bump 1.0
  + TranscEndence DevTest-33
  + GeneticChickengineering 1.2.1
  + ChestTerminal DEV - 43 (git 3096bab5)
  + AlchimiaVitae 1.0.0
  + HotbarPets UNOFFICIAL
  + SlimefunLuckyBlocks UNOFFICIAL
  - SlimefunZT 1.0.0
  + BeyondHorizons 1.0.2
  + FoxyMachines 1.0.0
  + SimpleMaterialGenerators 1.0.0
  + ElectricSpawners UNOFFICIAL
  + ExtraHeads DEV - 21 (git a2c68d59)
  + SlimyTreeTaps UNOFFICIAL
  + FlowerPower 1.0.0
  + FluffyMachines 84 - CH
  + DyedBackpacks 1.0.0
  + FireSlime RC-8
  + CargoExpansion 1.0.1
  + SensibleToolbox UNOFFICIAL
  + LiteXpansion MODIFIED
  + MagicXpansion 0.1.0
  - EnergyTools ${project.version}
  + PomaExpansion UNOFFICIAL
  + InfinityExpansion 144 - CH
  + DynaTech 1.0.0
  + SlimeQuest MODIFIED
  - SlimeCustomizer DEV - 8 (git 6fe1c3e1)
  + SlimeTinker MODIFIED
  + CMI 8.8.5.0
  + CMILib 1.0.2.6
  + Residence 5.0.0.0

Installed Plugins (116):
  + PlugMan 2.2.2
  + FarmProtect 1.9.0
  + ConsoleSpamFix 1.8.5
  + ChestSort 10.3.2
  + ViaVersion 4.0.0
  + EpicPluginLib 2.0
  + ViaBackwards 4.0.0
  + PlayerPlace 1.0
  + LuckPerms 5.3.46
  + CreeperConfetti 1.2.1
  + SAML 2.0.0
  + LoneLibs 1.0.9
  + ProtocolLib 4.6.1-SNAPSHOT-b505
  + InventoryRollbackPlus 1.6.1
  + Chunky 1.2.86
  + PlaceholderAPI 2.10.4
  + JoinMessagePlus 4.0
  + MultitoolPlus 1.5.13
  + SkinsRestorer 14.1.1
  + AutoRestart 4.1.5
  + PlayMoreSounds 4.0.2
  + LightAPI 3.4.6
  + ProtocolStringReplacer 1.1.3-beta
  + WorldEdit 7.1.0-SNAPSHOT;4825-8e55131
  + ServerJoin 1.0-SNAPSHOT
  + LibsDisguises 10.0.25
  + GraveEntitySpawn 1.1
  + DAutoMessage 1.4
  + CS-CoreLib DEV - 92 (git e9150d72)
  + floodgate-bukkit 1.0.0
  + HoloDrops 2.6
  + Vault 1.7.3-b${env.TRAVIS_BUILD_NUMBER}
  + Criticals 1.9
  + HolographicDisplays 2.4.6
  + Oh_the_dungeons_youll_go 15.3
  + spark 1.4.3
  + LiteSignIn 1.4.0
  + PixelVip 3.0.3
  + TrHologram 1.11
  + WorldGuard 7.0.4+f7ff984
  + WorldEditSUI 1.7.1
  + BentoBox 1.16.1
  + DeluxeMenus 1.13.3-Release
  + mcMMO 2.1.197-SNAPSHOT
  + Slimefun 1.1.9_货运极致优化
  + EcoPower DEV - 1 (git 53445ee5)
  + SimpleUtils DEV - 3 (git ee043364)
  + CompressedMachines 1.0.0
  + ExtraGear DEV - 12 (git 4570ea2c)
  + ClayTech violet-1.2.24
  + SFCalc UNOFFICIAL
  + EMC2 UNOFFICIAL
  + SlimeChem MODIFIED
  + NewBegginings 1.0.0
  + BloodAlchemy ALPHA - CH
  + SlimefunWarfare UNOFFICIAL
  + ExoticGarden DEV - 75 (git 6c3e5412)
  + Endrex 1.1.0
  + Liquid DEV - 10 (git 2277a85b)
  + SoulJars UNOFFICIAL
  + SlimyRepair 1.0.0
  + ExtraTools 1.2
  + HALsAddon 12
  + SlimefunOreChunks UNOFFICIAL
  + SlimeVoid 1.0
  + EnderPanda 1.0
  + PrivateStorage UNOFFICIAL
  + DankTech 1.2.6.1
  + SlimefunItemExpansion 1.0.2
  + SimpleStorage MODIFIED
  + SlimefunAddon 1.0.0
  + BetterFarming 1
  + Bump 1.0
  + UltimateTimber 2.0.9
  + BuildersWand 2.18.4
  + TranscEndence DevTest-33
  + GeneticChickengineering 1.2.1
  + ChestTerminal DEV - 43 (git 3096bab5)
  + Multiverse-Core 4.2.2-b812
  + DeluxeChat 1.16.2
  + AlchimiaVitae 1.0.0
  + HotbarPets UNOFFICIAL
  + SlimefunLuckyBlocks UNOFFICIAL
  - SlimefunZT 1.0.0
  + BeyondHorizons 1.0.2
  + FoxyMachines 1.0.0
  + SimpleMaterialGenerators 1.0.0
  + ElectricSpawners UNOFFICIAL
  + ExtraHeads DEV - 21 (git a2c68d59)
  + SlimyTreeTaps UNOFFICIAL
  + FlowerPower 1.0.0
  + FluffyMachines 84 - CH
  + DyedBackpacks 1.0.0
  + FireSlime RC-8
  + CargoExpansion 1.0.1
  + Multiverse-Inventories 4.2.2-b500
  + SensibleToolbox UNOFFICIAL
  + LiteXpansion MODIFIED
  + EliteMobs 7.3.1
  + AuthMe 5.6.0-SNAPSHOT-b2379
  + MagicXpansion 0.1.0
  - EnergyTools ${project.version}
  + PomaExpansion UNOFFICIAL
  + InfinityExpansion 144 - CH
  + InfiniteBot 1.5.0-SNAPSHOT
  + DynaTech 1.0.0
  + SlimeQuest MODIFIED
  - SlimeCustomizer DEV - 8 (git 6fe1c3e1)
  + SlimeTinker MODIFIED
  + CMI 8.8.5.0
  + Skript 2.5.3
  + skript-reflect 2.2.1
  + CMILib 1.0.2.6
  + Residence 5.0.0.0
  + QuickShop 4.0.8.6
  + JetsMinions 7.1.15

Block Info:
  World: sc
  X: -1142
  Y: 63
  Z: 55393
  Material: FURNACE
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftFurnaceFurace
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftFurnaceFurnace

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: COMPRESSED_ELECTRIC_SMELTERY_64
  Inventory: true
  Data: {"energy-charge":"4830","id":"COMPRESSED_ELECTRIC_SMELTERY_64"}

Stacktrace:

java.lang.IllegalAccessError: class slimefunmachines.CompressedElectricSmeltery tried to access private method 'void io.github.thebusybiscuit.slimefun4.utils.itemstack.ItemStackWrapper.<init>(org.bukkit.inventory.ItemStack)' (slimefunmachines.CompressedElectricSmeltery is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7a09ec8f; io.github.thebusybiscuit.slimefun4.utils.itemstack.ItemStackWrapper is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @7cd5fe50)
	at slimefunmachines.CompressedElectricSmeltery.findNextRecipe(CompressedElectricSmeltery.java:47)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer.tick(AContainer.java:367)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:336)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:180)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:167)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:137)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:106)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by LordIdra** [comment]
This *should* be fixed. However, I really don't recommend using this plugin because I can't guarantee bugs like this will be so easily fixable in the future.
